spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=SWP391_IMS;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
